# pubspec.yaml

name: wink_rider_app
description: Application Livreur pour WINK EXPRESS (Migration Flutter).
# La version et les configurations d'environnement peuvent varier
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Ajouté pour les localisations (DatePicker)
  flutter_localizations:
    sdk: flutter

  # HTTP Client pour les appels REST à l'API Node.js/Express
  dio: ^5.5.0

  # Gestion de l'état (facile à démarrer)
  provider: ^6.0.5

  # Gestion de l'authentification et du stockage local (token/user info)
  shared_preferences: ^2.2.3

  # Communication WebSocket pour le chat/notifications en temps réel
  web_socket_channel: ^3.0.0

  # Formatage et manipulation des dates
  # *** CORRECTION ICI (version mise à jour) ***
  intl: ^0.20.2

  # Notifications locales (pour imiter le son/badge du PWA actuel)
  flutter_local_notifications: ^17.2.4

  # Icônes (peut être optionnel si vous utilisez des icônes custom)
  cupertino_icons: ^1.0.8

  # Bibliothèque de graphiques (ajoutée pour l'écran Performance)
  fl_chart: ^0.68.0

  # Bibliothèque pour les confettis (ajoutée pour l'écran Performance)
  confetti: ^0.7.0

  # Dépendances ajoutées pour la synchronisation hors ligne
  sqflite: ^2.3.0             # Base de données locale
  path_provider: ^2.1.1       # Pour trouver le chemin de la DB
  path: ^1.8.3                # Manipulation de chemins (souvent requis avec sqflite)
  connectivity_plus: ^5.0.1   # Pour détecter les changements de connexion

  # Ajout de url_launcher
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

# Configuration spécifiques à Flutter
flutter:
  uses-material-design: true

  # Assets (ajoutez si vous avez des images ou polices à inclure, comme le logo)
  # assets:
  #  - lib/assets/audio/sound.mp3 # Ajout du son de notification
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # Fonts (si vous utilisez des polices personnalisées)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf pffl